config_version: 0.3
dynamic_swappiness:
  swappiness_range:
    max: 100
    min: 60
  threshold:
    cpu_pressure: 40
    memory_pressure: 15
    io_pressure: 30
    step: 2
virtual_memory:
  pressure_binding: false
  zram:
    activation_threshold: 70
    deactivation_threshold: 15
  swap:
    activation_threshold: 90
    deactivation_threshold: 25
